set nocompatible              " be iMproved, required
filetype off                  " required

if has('win32') || has ('win64')
  let plugPath='C:\Users\isdi\.config\nvim\plugged'
  
  "To use powershell (on Windows): >
  set shell=powershell shellquote=( shellpipe=\| shellredir=> shellxquote=
  set shellcmdflag=-NoLogo\ -NoProfile\ -ExecutionPolicy\ RemoteSigned\ -Command

  " Esc to leave terminal mode
  tnoremap <Esc> <C-\><C-n>

else
  let plugPath='~\.config\nvim\plugged'
endif

"call plug#begin('C:\Users\isdi\.config\nvim\plugged')
call plug#begin(plugPath)

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-git'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-rhubarb'
Plug 'jlanzarotta/bufexplorer'
Plug 'godlygeek/tabular'
Plug 'nachumk/systemverilog.vim'
Plug 'icymind/NeoSolarized'
Plug 'chrisbra/vim-diff-enhanced'
Plug 'scrooloose/nerdtree'
Plug 'triglav/vim-visual-increment'
Plug 'tomtom/tlib_vim'
Plug 'Yggdroot/indentLine'
Plug 'jeffkreeftmeijer/vim-numbertoggle'
Plug 'plasticboy/vim-markdown'
Plug 'flazz/vim-colorschemes'
Plug 'scrooloose/nerdcommenter'
call plug#end()
filetype plugin indent on    " required

set number relativenumber
"
" Map the leader key to SPACE
let mapleader="\<SPACE>"


" NERDTree configuation 
let NERDTreeShowLineNumbers=1
map <F2> :NERDTreeToggle<CR>
map <F3> :NERDTreeFind %<CR>
map <Leader>n :NERDTreeFocus<CR>


" Enable solarized
colorscheme NeoSolarized
set background=dark


 "Show all hidden characters except spaces
 set listchars=tab:>-,trail:~,extends:>,precedes:<
 set list
 

"Change Color theme
syntax enable
if has('gui_running')
    set background=dark
    colorscheme wombat
    "colorscheme solarized
    call togglebg#map("<F5>")
endif


 " Associate r files to XML syntax
 au BufNewFile,BufRead *.r setlocal ft=xml
" associate *.upf with Tcl filetype
au BufRead,BufNewFile *.upf set filetype=tcl
 
 set expandtab
 set tabstop=2
 set shiftwidth=2
 filetype indent on
 set hlsearch
 set number
 set nomousehide
 set mouse=a

" Can be typed even faster than jj, and if you are already in
"    normal mode, you (usually) don't accidentally move:
:imap kj <Esc>

" Remove = and : from the filename characters
set isfname-=:
set isfname-==

"Window navigation
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l


:set guioptions-=T  "remove toolbar

