set nocompatible              " be iMproved, required

" Map the leader key to SPACE
let mapleader="\<SPACE>"


" Esc to leave terminal mode
tnoremap <Esc> <C-\><C-n>


" ===================== Plugged configuration =========================
if has('win32') || has ('win64')
  let plugPath=expand('$USERPROFILE\.config\nvim\plugged')
else
  let plugPath='~/.config/.vim/plugged'
endif

" vim-plug can be installed from https://github.com/junegunn/vim-plug
call plug#begin(plugPath)

if has('nvim')
  " Look and feel
  Plug 'nvim-lua/plenary.nvim'
  Plug 'nvim-lua/popup.nvim'
  " Navigation
  Plug 'nvim-telescope/telescope.nvim'
  " Convinience
  Plug 'sindrets/diffview.nvim'
endif

" Look and feel
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'flazz/vim-colorschemes'

" Version control
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'juneedahamed/svnj.vim'

" Navigation
Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdtree'
Plug 'christoomey/vim-tmux-navigator'
Plug 'jlanzarotta/bufexplorer'

" Languages
Plug 'plasticboy/vim-markdown'
Plug 'nachumk/systemverilog.vim'
"
" Convinience 
Plug 'tpope/vim-surround'
Plug 'scrooloose/nerdcommenter'
Plug 'junegunn/vim-easy-align'
Plug 'tpope/vim-rhubarb'
Plug 'chrisbra/vim-diff-enhanced'
Plug 'triglav/vim-visual-increment'
Plug 'jeffkreeftmeijer/vim-numbertoggle'
Plug 'andymass/vim-matchup'
Plug 'AndrewRadev/linediff.vim'

" Vim mark and its required plugin
Plug 'inkarkat/vim-mark'
Plug 'inkarkat/vim-ingo-library'


" Windows only plugins
if has('win32') || has ('win64')
  Plug 'PProvost/vim-ps1'
endif

" This plugins must be instanciated last, since depends on all the previous
" Personal configurations
Plug '~/dotfiles/vim/brody-vim-config'

call plug#end()

